# Generated by Django 5.2 on 2025-04-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'STUDENT'), ('faculty', 'FACULTY')], max_length=10, null=True),
        ),
    ]
