# Generated by Django 5.2 on 2025-04-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_course_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='faculty_id',
            new_name='faculty',
        ),
    ]
