# Generated by Django 5.2 on 2025-04-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_faculty_id_course_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_assign',
            old_name='student_id',
            new_name='student',
        ),
    ]
