# Generated by Django 5.2 on 2025-04-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_course_assign_course_course_assign_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_assign',
        ),
    ]
