# Generated by Django 5.2 on 2025-04-08 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_course_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mood', models.CharField(choices=[('online', 'ONLINE MOOD'), ('offline', 'OFFLINE MOOD')], max_length=10)),
                ('paid_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.course')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
