# Generated by Django 5.2 on 2025-04-11 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assign_submit_check_by_assign_submit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_assign',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 20, 12, 17, 852728)),
        ),
    ]
